export type SuperQuizQuestion = {
  id: string;
  category: string;
  question: string;
  answer: string;
  options: string[];
  explanation: string;
};

export const desabilidadeSuperQuiz: SuperQuizQuestion[] = [
  {
    id: "des-super-01",
    category: "Desabilidade Funcional",
    question: "Qual é o objetivo central do cuidado à pessoa com desabilidade funcional?",
    answer: "Preservar autonomia, segurança, dignidade e participação nas atividades possíveis.",
    options: [
      "Realizar todas as tarefas pela pessoa.",
      "Preservar autonomia, segurança, dignidade e participação nas atividades possíveis.",
      "Evitar qualquer atividade que exija esforço.",
      "Priorizar apenas o diagnóstico clínico.",
    ],
    explanation: "O cuidado funcional deve apoiar capacidades preservadas e oferecer ajuda proporcional, sem substituir desnecessariamente a pessoa.",
  },
  {
    id: "des-super-02",
    category: "Desabilidade Funcional",
    question: "Qual alternativa contém apenas Atividades de Vida Diária (AVDs)?",
    answer: "Higiene, vestir-se, alimentação e uso do banheiro.",
    options: [
      "Compras, transporte, finanças e preparo de refeições.",
      "Higiene, vestir-se, alimentação e uso do banheiro.",
      "Uso de telefone, compras, transporte e organização de medicamentos.",
      "Trabalho, lazer, transporte e gestão financeira.",
    ],
    explanation: "AVDs são atividades básicas de autocuidado. Compras, transporte e tarefas domésticas mais complexas pertencem às AIVDs.",
  },
  {
    id: "des-super-03",
    category: "Desabilidade Funcional",
    question: "Qual exemplo representa uma Atividade Instrumental de Vida Diária (AIVD)?",
    answer: "Organizar compras e preparar uma refeição.",
    options: [
      "Escovar os dentes.",
      "Vestir uma camiseta.",
      "Organizar compras e preparar uma refeição.",
      "Transferir-se da cama para a cadeira.",
    ],
    explanation: "AIVDs envolvem tarefas mais complexas necessárias à vida independente, como compras, refeições, transporte e organização doméstica.",
  },
  {
    id: "des-super-04",
    category: "Desabilidade Funcional",
    question: "Antes de ajudar uma pessoa a caminhar com andador, qual cuidado é mais adequado?",
    answer: "Verificar ajuste, integridade, ambiente e capacidade atual da pessoa.",
    options: [
      "Aumentar a velocidade para reduzir o tempo de esforço.",
      "Verificar ajuste, integridade, ambiente e capacidade atual da pessoa.",
      "Retirar o dispositivo se a pessoa estiver insegura.",
      "Segurar a pessoa pelos braços durante todo o trajeto.",
    ],
    explanation: "O dispositivo e o ambiente precisam estar seguros, e a capacidade funcional deve ser considerada antes de iniciar a marcha.",
  },
  {
    id: "des-super-05",
    category: "Desabilidade Funcional",
    question: "Durante uma transferência do leito para a cadeira, o que deve ser feito antes de iniciar?",
    answer: "Preparar o destino, explicar o movimento e verificar se é necessária ajuda adicional.",
    options: [
      "Puxar a pessoa rapidamente pelos braços.",
      "Preparar o destino, explicar o movimento e verificar se é necessária ajuda adicional.",
      "Manter a cadeira destravada para facilitar o giro.",
      "Iniciar o movimento sem explicar para evitar ansiedade.",
    ],
    explanation: "Planejamento, comunicação e preparação do ambiente reduzem risco para a pessoa e para o cuidador.",
  },
  {
    id: "des-super-06",
    category: "Desabilidade Funcional",
    question: "Qual atitude melhor representa ajuda proporcional?",
    answer: "Oferecer apenas o apoio necessário e permitir que a pessoa faça o que consegue com segurança.",
    options: [
      "Fazer tudo pela pessoa para economizar tempo.",
      "Oferecer apenas o apoio necessário e permitir que a pessoa faça o que consegue com segurança.",
      "Evitar qualquer ajuda mesmo quando existe risco.",
      "Substituir dispositivos de apoio por assistência manual sempre.",
    ],
    explanation: "Ajuda proporcional preserva independência e reduz dependência desnecessária, sem ignorar riscos reais.",
  },
  {
    id: "des-super-07",
    category: "Desabilidade Funcional",
    question: "Qual situação ambiental aumenta o risco de queda?",
    answer: "Tapete solto em uma área de passagem.",
    options: [
      "Boa iluminação no percurso.",
      "Barra de apoio bem fixada.",
      "Tapete solto em uma área de passagem.",
      "Campainha ao alcance da pessoa.",
    ],
    explanation: "Tapetes soltos são obstáculos frequentes e podem favorecer tropeços, especialmente em pessoas com mobilidade reduzida.",
  },
  {
    id: "des-super-08",
    category: "Desabilidade Funcional",
    question: "Qual é a forma mais adequada de se comunicar com uma pessoa com limitação funcional?",
    answer: "Falar diretamente com a pessoa e perguntar como prefere receber ajuda ou informação.",
    options: [
      "Falar somente com o acompanhante.",
      "Usar linguagem infantil para simplificar.",
      "Falar diretamente com a pessoa e perguntar como prefere receber ajuda ou informação.",
      "Presumir que não compreende se usa dispositivo de apoio.",
    ],
    explanation: "A comunicação deve ser direta, respeitosa e centrada na pessoa, sem pressupor incapacidade.",
  },
  {
    id: "des-super-09",
    category: "Desabilidade Funcional",
    question: "Por que óculos, aparelho auditivo, bengala ou comunicador devem permanecer acessíveis quando necessários?",
    answer: "Porque favorecem autonomia, orientação, segurança e participação.",
    options: [
      "Porque substituem a necessidade de avaliação funcional.",
      "Porque favorecem autonomia, orientação, segurança e participação.",
      "Porque devem ser usados apenas durante terapia.",
      "Porque reduzem a necessidade de comunicação com a equipe.",
    ],
    explanation: "Recursos pessoais e dispositivos de apoio ampliam capacidade funcional e participação nas atividades.",
  },
  {
    id: "des-super-10",
    category: "Desabilidade Funcional",
    question: "Qual comportamento deve ser evitado no cuidado à pessoa com desabilidade funcional?",
    answer: "Infantilizar e assumir que ela é incapaz sem avaliar suas capacidades.",
    options: [
      "Perguntar preferências.",
      "Adaptar o ambiente.",
      "Infantilizar e assumir que ela é incapaz sem avaliar suas capacidades.",
      "Estimular participação segura.",
    ],
    explanation: "Limitação funcional não elimina autonomia decisória nem capacidades preservadas; pressupostos podem aumentar dependência e reduzir dignidade.",
  },
  {
    id: "des-super-11",
    category: "Desabilidade Funcional",
    question: "Uma pessoa que antes caminhava com segurança começa a apresentar nova instabilidade. Qual é a conduta adequada?",
    answer: "Interromper a atividade se houver risco, garantir segurança e comunicar a mudança à equipe.",
    options: [
      "Continuar a caminhada para fortalecer a musculatura.",
      "Interromper a atividade se houver risco, garantir segurança e comunicar a mudança à equipe.",
      "Retirar definitivamente o dispositivo de apoio.",
      "Ignorar a mudança se não houve queda.",
    ],
    explanation: "Mudança funcional recente pode indicar novo risco e deve ser observada, registrada e comunicada conforme o contexto assistencial.",
  },
  {
    id: "des-super-12",
    category: "Desabilidade Funcional",
    question: "Qual é o principal objetivo de adaptar o ambiente para uma pessoa com limitação funcional?",
    answer: "Reduzir barreiras e permitir participação com maior segurança e independência.",
    options: [
      "Impedir que a pessoa realize atividades sozinha.",
      "Reduzir barreiras e permitir participação com maior segurança e independência.",
      "Eliminar a necessidade de qualquer dispositivo de apoio.",
      "Padronizar o ambiente para todos, sem considerar necessidades individuais.",
    ],
    explanation: "Acessibilidade ambiental reduz obstáculos e favorece autonomia e participação.",
  },
  {
    id: "des-super-13",
    category: "Desabilidade Funcional",
    question: "Em uma cadeira de rodas, qual item deve ser verificado antes de uma transferência quando aplicável?",
    answer: "Freios e estabilidade da cadeira.",
    options: [
      "Apenas a cor do assento.",
      "Freios e estabilidade da cadeira.",
      "Somente a altura do encosto.",
      "Apenas o peso do cuidador.",
    ],
    explanation: "Freios e estabilidade ajudam a evitar deslocamento inesperado durante a transferência.",
  },
  {
    id: "des-super-14",
    category: "Desabilidade Funcional",
    question: "Qual fator pessoal pode aumentar o risco de queda?",
    answer: "Tontura e alteração do equilíbrio.",
    options: [
      "Boa iluminação.",
      "Calçado adequado.",
      "Tontura e alteração do equilíbrio.",
      "Barra de apoio disponível.",
    ],
    explanation: "Tontura e alteração de equilíbrio comprometem estabilidade e aumentam o risco de queda.",
  },
  {
    id: "des-super-15",
    category: "Desabilidade Funcional",
    question: "Qual situação indica necessidade de reavaliar o plano de ajuda funcional?",
    answer: "A pessoa passa a necessitar mais apoio para uma atividade que antes realizava sozinha.",
    options: [
      "A pessoa mantém o mesmo desempenho habitual.",
      "A pessoa passa a necessitar mais apoio para uma atividade que antes realizava sozinha.",
      "O cuidador prefere executar a tarefa mais rapidamente.",
      "O ambiente permanece sem alterações e sem riscos.",
    ],
    explanation: "Mudança na capacidade de realizar atividades é um sinal importante para reavaliar necessidades e segurança.",
  },
  {
    id: "des-super-16",
    category: "Desabilidade Funcional",
    question: "Qual atitude favorece autonomia durante a higiene pessoal?",
    answer: "Organizar os materiais ao alcance e deixar a pessoa realizar as etapas que consegue com segurança.",
    options: [
      "Realizar todo o banho sem permitir participação.",
      "Organizar os materiais ao alcance e deixar a pessoa realizar as etapas que consegue com segurança.",
      "Retirar todos os dispositivos de apoio antes da higiene.",
      "Apressar a pessoa para reduzir o tempo do cuidado.",
    ],
    explanation: "Organização e tempo adequado permitem maior participação e ajudam a preservar habilidades.",
  },
  {
    id: "des-super-17",
    category: "Desabilidade Funcional",
    question: "Ao apoiar uma pessoa com deficiência visual, qual atitude é mais adequada?",
    answer: "Apresentar-se, falar diretamente e oferecer orientação ou ajuda perguntando antes como prefere.",
    options: [
      "Puxar a pessoa pelo braço sem aviso.",
      "Falar apenas com quem a acompanha.",
      "Apresentar-se, falar diretamente e oferecer orientação ou ajuda perguntando antes como prefere.",
      "Mover seus objetos pessoais sem informar.",
    ],
    explanation: "Comunicação clara e consentimento ajudam a manter orientação, autonomia e segurança.",
  },
  {
    id: "des-super-18",
    category: "Desabilidade Funcional",
    question: "Qual princípio deve orientar o uso de dispositivos de apoio?",
    answer: "O dispositivo deve ser adequado, ajustado e usado conforme a necessidade individual.",
    options: [
      "O mesmo dispositivo serve para qualquer pessoa.",
      "O dispositivo deve ser adequado, ajustado e usado conforme a necessidade individual.",
      "Quanto maior o dispositivo, maior a segurança.",
      "Dispositivos devem substituir totalmente a mobilidade ativa.",
    ],
    explanation: "A escolha e o ajuste precisam considerar características individuais, funcionalidade e avaliação profissional.",
  },
  {
    id: "des-super-19",
    category: "Desabilidade Funcional",
    question: "Qual é um exemplo de cuidado centrado na pessoa?",
    answer: "Combinar medidas de segurança com as preferências e objetivos funcionais da pessoa.",
    options: [
      "Aplicar a mesma rotina para todos.",
      "Combinar medidas de segurança com as preferências e objetivos funcionais da pessoa.",
      "Decidir sem consultar a pessoa para evitar atrasos.",
      "Priorizar conveniência da equipe acima da participação da pessoa.",
    ],
    explanation: "Cuidado centrado na pessoa considera objetivos, preferências, dignidade e segurança de forma conjunta.",
  },
  {
    id: "des-super-20",
    category: "Desabilidade Funcional",
    question: "Após uma quase queda, mesmo sem lesão aparente, qual conduta é mais adequada?",
    answer: "Garantir segurança, observar a pessoa, comunicar e registrar conforme o protocolo do serviço.",
    options: [
      "Não fazer nada porque não houve queda completa.",
      "Garantir segurança, observar a pessoa, comunicar e registrar conforme o protocolo do serviço.",
      "Suspender toda mobilidade permanentemente.",
      "Trocar o dispositivo sem avaliação.",
    ],
    explanation: "Quase quedas podem revelar riscos importantes e devem ser consideradas para prevenção de novos eventos.",
  },
];
