export type StudyCard = { category: string; question: string; answer: string };
const c = (category: string, pairs: [string, string][]): StudyCard[] => pairs.map(([question, answer]) => ({ category, question, answer }));
export const studyCards: StudyCard[] = [
...c("Fundamentos",[
["O que significa SAE?","Sistematização da Assistência de Enfermagem."],
["Qual é a primeira etapa do processo de enfermagem?","Avaliação de enfermagem, com coleta de dados subjetivos e objetivos."],
["Quais são as cinco etapas do processo de enfermagem?","Avaliação, diagnóstico, planejamento, implementação e evolução."],
["Por que higienizar as mãos?","Para interromper a transmissão de microrganismos e prevenir infecções."],
["Quando medir sinais vitais?","Na admissão, conforme prescrição ou protocolo, antes e após procedimentos e diante de alterações clínicas."],
["Qual a frequência respiratória usual do adulto em repouso?","Geralmente de 12 a 20 incursões respiratórias por minuto."],
["O que é pulso?","A expansão rítmica de uma artéria produzida pela ejeção de sangue do coração."],
["O que é pressão arterial?","A força exercida pelo sangue sobre as paredes arteriais."],
["O que avaliar na dor?","Localização, intensidade, qualidade, início, duração, fatores de melhora e piora."],
["Para que serve a escala numérica de dor?","Para a pessoa classificar a intensidade da dor, geralmente de zero a dez."],
["O que é registro de enfermagem?","Documentação objetiva, cronológica e legível dos cuidados e respostas do paciente."],
["Por que identificar o paciente com dois dados?","Para reduzir trocas e eventos adversos durante o cuidado."],
["O que significa técnica asséptica?","Conjunto de medidas para evitar a contaminação por microrganismos."],
["O que observar na pele?","Cor, temperatura, umidade, integridade, edema, dor e presença de lesões."],
["Qual o objetivo da mudança de decúbito?","Reduzir pressão prolongada, promover conforto e prevenir lesões por pressão."],
["O que é balanço hídrico?","Registro e comparação dos líquidos ingeridos, administrados e eliminados."],
["O que fazer antes de qualquer procedimento?","Confirmar indicação, identificar o paciente, explicar o procedimento e higienizar as mãos."]
]),
...c("Urgência e emergência",[
["O que representa o A no ABCDE?","Avaliação da via aérea com proteção da coluna cervical quando indicada."],
["O que representa o B no ABCDE?","Respiração e ventilação."],
["O que representa o C no ABCDE?","Circulação e controle de hemorragias."],
["O que representa o D no ABCDE?","Avaliação neurológica rápida."],
["O que representa o E no ABCDE?","Exposição do paciente com prevenção de hipotermia."],
["Qual é o objetivo da triagem?","Priorizar o atendimento segundo gravidade e risco, não por ordem de chegada."],
["O que é uma emergência?","Condição com risco imediato de morte ou dano grave que exige intervenção rápida."],
["O que é uma urgência?","Condição que necessita atendimento rápido, mas pode não apresentar risco imediato de morte."],
["Qual o primeiro cuidado em uma cena?","Verificar a segurança do local antes de se aproximar."],
["O que fazer ao encontrar pessoa inconsciente?","Avaliar responsividade, acionar ajuda e seguir o protocolo de suporte básico de vida."],
["Para que serve o DEA?","Analisar o ritmo cardíaco e indicar choque quando apropriado."],
["O que observar na respiração?","Frequência, profundidade, ritmo, esforço, sons e coloração."],
["Qual sinal pode indicar má perfusão?","Pele fria ou pálida, enchimento capilar lento, confusão ou pulso fraco."],
["Como agir diante de sangramento externo importante?","Aplicar pressão direta e acionar atendimento de emergência conforme protocolo."],
["Por que prevenir hipotermia no trauma?","Porque a perda de calor pode agravar sangramento e instabilidade."],
["O que deve ser conferido no carrinho de emergência?","Lacre, validade, materiais, medicamentos, oxigênio e funcionamento dos equipamentos."],
["Quando chamar o serviço de emergência?","Diante de risco à vida, inconsciência, dificuldade respiratória importante, dor torácica ou outros sinais graves."]
]),
...c("Farmacologia",[
["Quais são os cinco certos clássicos?","Paciente, medicamento, dose, via e horário certos."],
["O que conferir antes de administrar um medicamento?","Prescrição, identificação, alergias, medicamento, dose, via, horário, validade e integridade."],
["Por que perguntar sobre alergias?","Para prevenir reações alérgicas potencialmente graves."],
["O que é via oral?","Administração do medicamento pela boca."],
["O que é via sublingual?","Administração sob a língua para absorção pela mucosa."],
["O que significa uso tópico?","Aplicação sobre pele ou mucosa para efeito local ou sistêmico."],
["O que é efeito adverso?","Efeito indesejado associado ao uso de um medicamento."],
["O que é contraindicação?","Situação em que o uso pode causar risco maior que o benefício."],
["Por que não triturar todo comprimido?","Alguns têm revestimento ou liberação modificada e triturá-los altera segurança e efeito."],
["O que fazer diante de prescrição ilegível ou duvidosa?","Não administrar até esclarecer com o profissional responsável."],
["O que é dupla checagem?","Conferência independente por dois profissionais quando exigida pelo protocolo."],
["Como evitar contaminação no preparo?","Higienizar mãos e bancada, usar técnica asséptica e evitar tocar partes críticas."],
["Por que rotular uma preparação?","Para manter identificação, dose, horário e segurança até a administração."],
["O que é dose prescrita?","Quantidade do medicamento determinada para o paciente."],
["O que é dose disponível?","Quantidade ou concentração apresentada no produto disponível."],
["Quando registrar a administração?","Imediatamente após administrar, conforme normas da instituição."],
["O que fazer se o paciente recusar?","Não forçar; orientar, investigar o motivo, comunicar e registrar."]
]),
...c("Saúde da criança",[
["Por que usar equipamento pediátrico adequado?","Para obter medidas confiáveis e evitar desconforto ou lesão."],
["Como contar a respiração de uma criança pequena?","Preferencialmente antes de manipulá-la, observando movimentos por um minuto."],
["O que a curva de crescimento acompanha?","Evolução de peso, comprimento ou altura e outros indicadores ao longo do tempo."],
["Por que pesar o bebê sem excesso de roupas?","Para aumentar a precisão e permitir comparação adequada."],
["O que observar antes de tocar a criança?","Estado geral, cor, respiração, interação, postura e comportamento."],
["Qual a importância do acompanhante?","Oferece segurança, informa hábitos e participa do cuidado."],
["Como reduzir medo durante procedimentos?","Explicar de modo apropriado à idade, permitir acompanhante e usar estratégias lúdicas."],
["O que conferir antes de uma vacina?","Identificação, indicação, histórico, validade, conservação e possíveis contraindicações."],
["Por que registrar a vacinação?","Para documentar dose, data, lote, local e continuidade do esquema."],
["O que é puericultura?","Acompanhamento integral do crescimento e desenvolvimento infantil."],
["O que avaliar na hidratação infantil?","Mucosas, lágrimas, diurese, estado geral e outros sinais clínicos."],
["Por que a dose pediátrica exige atenção especial?","Frequentemente depende de peso ou superfície corporal e requer cálculo preciso."],
["Como verificar a identificação de uma criança?","Usar pulseira e pelo menos dois identificadores, confirmando com o responsável."],
["O que é desenvolvimento infantil?","Aquisição progressiva de habilidades motoras, cognitivas, sociais e de linguagem."],
["Qual cuidado ao medir pressão em criança?","Selecionar manguito com tamanho adequado ao braço."],
["Quando comunicar alteração em criança?","Sempre que houver mudança de comportamento, respiração, consciência, perfusão ou sinais vitais."]
]),
...c("Saúde do adulto",[
["Qual o objetivo da avaliação funcional?","Identificar capacidade e necessidade de ajuda nas atividades diárias."],
["Como reduzir risco de queda?","Manter ambiente livre, campainha acessível, calçado seguro e assistência conforme avaliação."],
["Por que estimular mobilidade segura?","Para preservar força, circulação, função respiratória e independência."],
["O que é lesão por pressão?","Dano na pele ou tecido por pressão, cisalhamento ou combinação desses fatores."],
["Quais áreas têm maior risco de pressão?","Proeminências ósseas, como sacro, calcanhares, quadris e cotovelos."],
["O que observar na mudança de decúbito?","Pele, dor, dispositivos, alinhamento, conforto e segurança."],
["Por que elevar grades com critério?","Para segurança quando indicadas, sem substituir avaliação e vigilância."],
["O que registrar no balanço hídrico?","Todos os volumes de entrada e saída no período definido."],
["O que pode indicar desidratação?","Sede, mucosas secas, redução de diurese, tontura e alterações clínicas."],
["O que pode indicar edema?","Aumento de volume, pele estirada e depressão após pressão em alguns casos."],
["Como auxiliar na marcha?","Avaliar tolerância, usar técnica e dispositivo adequados e permanecer ao lado."],
["Por que orientar respiração e tosse quando prescritas?","Para favorecer expansão pulmonar e mobilização de secreções."],
["O que é cuidado centrado na pessoa?","Cuidado que respeita preferências, valores, necessidades e participação do paciente."],
["Como preservar privacidade?","Usar biombo ou cortina, cobrir áreas não examinadas e limitar exposição."],
["Por que reconciliar medicamentos?","Para comparar medicamentos em uso e reduzir omissões, duplicidades e interações."],
["O que observar na alimentação?","Aceitação, dificuldade para engolir, náusea, restrições e necessidade de ajuda."]
]),
...c("Anatomia e fisiologia",[
["Qual é a função principal do coração?","Bombear sangue para os pulmões e para os tecidos do corpo."],
["Qual órgão realiza as trocas gasosas?","Os pulmões, especialmente nos alvéolos."],
["O que é inspiração?","Entrada de ar nos pulmões."],
["O que é expiração?","Saída de ar dos pulmões."],
["Qual a função das artérias?","Levar sangue para fora do coração."],
["Qual a função das veias?","Conduzir sangue de volta ao coração."],
["Qual a função dos capilares?","Permitir trocas de gases, nutrientes e resíduos entre sangue e tecidos."],
["Qual a função principal dos rins?","Filtrar o sangue, formar urina e ajudar no equilíbrio de líquidos e eletrólitos."],
["Qual a função do fígado?","Participar do metabolismo, produzir bile, armazenar nutrientes e processar substâncias."],
["Onde começa a digestão?","Na boca, com mastigação e ação da saliva."],
["Qual a função do estômago?","Armazenar e misturar alimentos, iniciando etapas importantes da digestão."],
["Onde ocorre grande parte da absorção de nutrientes?","No intestino delgado."],
["Qual a função principal do intestino grosso?","Absorver água e formar as fezes."],
["Qual órgão coordena o sistema nervoso?","O encéfalo, em conjunto com medula e nervos."],
["Qual a função dos músculos?","Produzir movimento, manter postura e gerar calor."],
["Qual a função do esqueleto?","Sustentar, proteger órgãos, permitir movimento e armazenar minerais."],
["O que é homeostase?","Manutenção de condições internas relativamente estáveis no organismo."]
]),
...c("Geriatria",[
["O que é avaliação funcional da pessoa idosa?","Avaliação da capacidade para realizar atividades da vida diária e do nível de ajuda necessário."],
["Por que a prevenção de quedas é importante na pessoa idosa?","Porque quedas podem causar lesões, perda de independência e complicações importantes."],
["O que observar ao avaliar risco de queda?","Marcha, equilíbrio, visão, tontura, ambiente, dispositivos de apoio e fatores clínicos relevantes."],
["O que significa polifarmácia?","Uso simultâneo de vários medicamentos, situação que exige revisão e conciliação cuidadosas."],
["O que fazer diante de mudança aguda de confusão em pessoa idosa?","Reconhecer como alteração importante, garantir segurança e comunicar para avaliação clínica."],
["O que é delirium?","Síndrome de início agudo e curso flutuante com alteração de atenção e cognição, que requer avaliação da causa."],
["Como preservar autonomia no cuidado?","Incluir a pessoa nas decisões e estimular o que consegue realizar com segurança."],
["Por que revisar a lista de medicamentos?","Para identificar discrepâncias, duplicidades, dificuldades de adesão e possíveis riscos a serem avaliados pela equipe."],
["Que cuidados ajudam a proteger a pele da pessoa idosa?","Inspeção regular, manejo de umidade, reposicionamento quando indicado e cuidado com fricção e pressão."],
["Por que a hidratação merece atenção na pessoa idosa?","Alterações de percepção de sede, doenças e medicamentos podem aumentar o risco de desequilíbrios hídricos."],
["O que observar na alimentação da pessoa idosa?","Aceitação, mastigação, deglutição, perda de peso, restrições e necessidade de ajuda."],
["O que é cuidado centrado na pessoa?","Cuidado que considera preferências, valores, história, objetivos e participação da pessoa."],
["Como favorecer orientação no ambiente?","Manter iluminação adequada, relógio ou calendário visíveis e comunicação simples e frequente quando necessário."],
["Por que mudanças súbitas de mobilidade merecem atenção?","Porque podem indicar alteração clínica, dor, efeito de medicamento ou maior risco de queda."],
["Qual o papel da família ou cuidador?","Compartilhar informações, participar do plano de cuidado quando apropriado e apoiar continuidade e segurança."],
["O que registrar após uma intercorrência?","Achados objetivos, medidas realizadas, resposta observada e comunicação feita conforme normas do serviço."]
]),
];
